---
metal_set_resource_limits: no
metal_check_api_health_endpoint: http://api.0.0.0.0.xip.io:8080/metal/v1/health

# metal_helm_chart_local_path: /helm-charts/charts/metal-control-plane

metal_api_replicas: 1
metal_api_view_key: metal-view
metal_api_edit_key: metal-edit
metal_api_admin_key: metal-admin

metal_api_nsq_tcp_address: nsqd:4150

metal_api_images:
- id: firewall-ubuntu-2.0.20201126
  name: Firewall 2 Ubuntu 20201126
  description: Firewall 2 Ubuntu 20201126
  url: https://images.metal-pod.io/metal-os/pull_requests/70-ipv6/firewall/2.0-ubuntu/20210204/img.tar.lz4
  features:
    - firewall
- id: ubuntu-20.04.20201126
  name: Ubuntu 20.04 20201126
  description: Ubuntu 20.04 20201126
  url: https://images.metal-stack.io/metal-os/pull_requests/70-ipv6/ubuntu/20.04/20210204/img.tar.lz4
  features:
    - machine

metal_api_sizes:
- id: v1-small-x86
  name: v1-small-x86
  description: The Tiny Virtual
  constraints:
  - type: cores
    min: 1
    max: 4
  - type: memory
    min: "{{ '500MB' | humanfriendly }}"
    max: "{{ '4GB' | humanfriendly }}"
  - type: storage
    min: "{{ '1GB' | humanfriendly }}"
    max: "{{ '10GB' | humanfriendly }}"

metal_api_partitions:
  - id: vagrant
    name: Vagrant Lab
    description: The vagrant lab
    bootconfig:
      kernelurl: "{{ metal_kernel_url }}"
      imageurl: "{{ metal_hammer_image_url }}"
      commandline: console=ttyS0,115200n8 ip=dhcp carrier_timeout=10
    privatenetworkprefixlength: 22

metal_api_networks:
- id: tenant-super-network-vagrant
  name: "Project Super Network"
  description: "Super network of all project networks"
  nat: false
  privatesuper: true
  underlay: false
  destinationprefixes: []
  partitionid: "vagrant"
  prefixes:
  - 10.0.0.0/16
  childprefixlength: 22
# - id: ipv6-super
#   name: IPv6 Super Network
#   description: IPv6 Super Network
#   destinationprefixes: []
#   nat: false
#   partitionid: vagrant
#   prefixes:
#   - fdbb::/50
#   privatesuper: true
#   vrf: 104006
#   childprefixlength: 64
- id: internet-vagrant-lab
  name: "Virtual Internet Network"
  description: "Virtual Internet Network for vagrant-lab"
  nat: true
  privatesuper: false
  underlay: false
  destinationprefixes:
    - 0.0.0.0/0
  partitionid: "vagrant"
  vrf: 104009
  prefixes:
  - 100.255.254.0/24
- id: ipv6-internet
  description: IPv6
  name: IPv6 Internet Network
  nat: true
  parentnetworkid: ""
  partitionid: vagrant
  destinationprefixes:
      - ::/0
  prefixes:
      - fdaa::/104
  privatesuper: false
  projectid: ""
  vrf: 104008
- id: underlay-vagrant-lab
  name: "Underlay Network"
  description: "Underlay Network for vagrant-lab"
  nat: false
  privatesuper: false
  underlay: true
  destinationprefixes: []
  partitionid: "vagrant"
  prefixes:
  - 10.1.0.0/24

metal_api_nsq_tls_enabled: false

metal_masterdata_api_tls_ca: "{{ lookup('file', 'certs/ca.pem') }}"
metal_masterdata_api_tls_cert: "{{ lookup('file', 'certs/masterdata-api/server.pem') }}"
metal_masterdata_api_tls_cert_key: "{{ lookup('file', 'certs/masterdata-api/server-key.pem') }}"
metal_masterdata_api_tls_client_cert: "{{ lookup('file', 'certs/masterdata-api/client.pem') }}"
metal_masterdata_api_tls_client_key: "{{ lookup('file', 'certs/masterdata-api/client-key.pem') }}"

# for metal-api development with kube-fwd
metal_masterdata_api_port: 8445

metal_masterdata_api_tenants:
- meta:
    id: fits
    kind: Tenant
    apiversion: v1
    version: 0
  name: FI-TS
  iam_config:
    issuer_config:
      url: ""
      client_id: "auth-go-cli"
    idm_config:
      idm_type: "UX"
    group_config:
      namespace_max_length: 20
  description: FI-TS tenant, which is provider

metal_masterdata_api_projects:
- meta:
    id: 00000000-0000-0000-0000-000000000001
    kind: Project
    apiversion: v1
    version: 0
  name: gardener-seeds
  description: Gardener Seeds Project

metal_console_replicas: 1

metal_api_grpc_certs_server_key: "{{ lookup('file', 'certs/grpc/server-key.pem') }}"
metal_api_grpc_certs_server_cert: "{{  lookup('file', 'certs/grpc/server.pem') }}"
metal_api_grpc_certs_client_key: "{{ lookup('file', 'certs/grpc/client-key.pem') }}"
metal_api_grpc_certs_client_cert: "{{  lookup('file', 'certs/grpc/client.pem') }}"
metal_api_grpc_certs_ca_cert: "{{ lookup('file', 'certs/ca.pem') }}"
